version: '3.8'

services:
  # AKTools 数据服务
  aktools:
    build:
      context: ..
      dockerfile: docker/aktools.Dockerfile
    container_name: stock-aktools
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./volumes/aktools-data:/app/data
      - ./volumes/aktools-logs:/app/logs
    networks:
      - stock-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Stock-A-Future 主应用
  stock-a-future:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: stock-a-future-app
    ports:
      - "8081:8081"
    environment:
      # 从配置文件加载环境变量
      - DATA_SOURCE_TYPE=aktools
      - AKTOOLS_BASE_URL=http://aktools:8080
      - SERVER_PORT=8081
      - SERVER_HOST=0.0.0.0
      - LOG_LEVEL=info
      - LOG_FORMAT=json
      - LOG_OUTPUT=both
      - LOG_FILENAME=logs/app.log
      - LOG_MAX_SIZE=100
      - LOG_MAX_BACKUPS=5
      - LOG_MAX_AGE=30
      - LOG_COMPRESS=true
      - LOG_CONSOLE_FORMAT=color
      - LOG_SHOW_CALLER=true
      - LOG_SHOW_TIME=true
      - CACHE_ENABLED=true
      - CACHE_DEFAULT_TTL=1h
      - CACHE_MAX_AGE=24h
      - CACHE_CLEANUP_INTERVAL=10m
      - PATTERN_PREDICTION_DAYS=14
      - CLEANUP_ENABLED=true
      - CLEANUP_INTERVAL=24h
      - CLEANUP_RETENTION_DAYS=30
    volumes:
      - ./volumes/data:/app/data
      - ./volumes/logs:/app/logs
    networks:
      - stock-network
    depends_on:
      aktools:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  stock-network:
    driver: bridge
    name: stock-network

volumes:
  # 数据持久化卷
  stock-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/data
  
  # 日志持久化卷  
  stock-logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/logs
      
  # AKTools 数据卷
  aktools-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/aktools-data
      
  # AKTools 日志卷
  aktools-logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/aktools-logs
