# 开发模式的 Docker Compose 配置
# 使用方法: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

version: '3.8'

services:
  stock-a-future:
    # 开发模式下挂载源码目录，支持热重载
    volumes:
      - ../:/app/src:ro  # 只读挂载源码
      - ./volumes/data:/app/data
      - ./volumes/logs:/app/logs
    environment:
      # 开发模式环境变量
      - LOG_LEVEL=debug
      - LOG_FORMAT=text
      - LOG_CONSOLE_FORMAT=color
    # 开发模式下使用 go run 而不是编译后的二进制
    command: ["sh", "-c", "cd /app/src && go run cmd/server/main.go"]
    # 开发模式下禁用健康检查，避免频繁重启
    healthcheck:
      disable: true
